### ISSUE TITLE
running it on CPU?

### ISSUE THREAD

**Issue by PradeepThapa** [ucbdrive/few-shot-object-detection#112]
Hi,

How can I run run_experiments.py in CPU?

**Comment by xinw1012** [comment]
Hi, sorry for the delayed response.  Our current configurations and results were obtained on multi-GPU settings.   Since our codebase is built upon `detectron2`,  if you could run the vanilla detectron2 on CPU only, you should be able to use or adapt our current codebase.  I found the prebuilt detectron2 on CPU here https://detectron2.readthedocs.io/en/latest/tutorials/install.html so you might try to install the corresponding detectron2 version.  We would appreciate it if you could keep this thread open and let us know if the current codebase is compatible with the CPU-only version.  We would be happy to keep it compatible.  PR would be highly appreciated!

Thanks for your interest in our work!

**Comment by slgxmh** [comment]
Add this config in your config yaml.

```YAML
MODEL:
  DEVICE: "cpu"
```
