### ISSUE TITLE
RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at ...)

### ISSUE THREAD

**Issue by a07913838438** [ucbdrive/few-shot-object-detection#129]
Thanks for your great projects and Thanks for share the code of your great work!
  My enviroment
  torch:1.4.0
  torchvision:0.5.0
  cuda:10.0
I have done all the installations shown on README but still, I get his error message whenever I try to do demo.py
RuntimeError: CUDA error: invalid device function(......)
can you give me any advice?thanks very much.

**Comment by shreyas-afk** [comment]
It might be because torch and cuda version required is incompatible (mine was same issue but with detectron2), after a lot of trial and error i found that this combination works
pip install torch==1.5.0+cu101 torchvision==0.6+cu101  -f https://download.pytorch.org/whl/torch_stable.html

**Comment by thomasehuang** [comment]
As @shreyas-afk said, this is probably due to incompatibility issues. Once you install pytorch for your cuda version, you can refer to [this page](https://github.com/facebookresearch/detectron2/releases/tag/v0.2.1) for the correct pre-built version of detectron2 that we use.

The README is a little outdated, so following it exactly may lead to packages being incompatible with the rest of the code base. I'll update it and you can try to follow it again and see if you still run into the issues.

**Comment by thomasehuang** [comment]
Just updated the installation instructions, you can try following it again. Will close this for now, but feel free to reopen it if it's still an issue for you.
