### ISSUE TITLE
train on a custom dataset

### ISSUE THREAD

**Issue by ElifErarslan1** [ucbdrive/few-shot-object-detection#130]
Hello, 
Could you please provide information about how to use FsDet on a custom dataset with VOC format?

**Comment by AISoltani** [comment]
> Hello,
> Could you please provide information about how to use FsDet on a custom dataset with VOC format?

hello, first you need to edit builtin and meta_builtin and also based on your dataset that like pascal or coco, you need to edit prepare_voc or coco too...run prepare to generate seed and not need to run both first file.

**Comment by thomasehuang** [comment]
As @AISoltani said, the protocol for creating a custom dataset is to create your dataset file in `fsdet/data` and update `fsdet/data/builtin.py` to register dataset paths and `fsdet/data/builtin_meta.py` to include meta information.

Since you said your dataset is in VOC format, you should just be able to use the VOC dataset file and only need to update `fsdet/data/builtin.py` and potentially `fsdet/data/builtin_meta.py`. Refer to the VOC portions of the code as example.

**Comment by thomasehuang** [comment]
Added more detailed instructions for custom datasets in the README [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/CUSTOM.md). Hope that helps!
