### ISSUE TITLE
Different training paradigm for VOC and COCO

### ISSUE THREAD

**Issue by tonysy** [ucbdrive/few-shot-object-detection#18]
Hi, I have a question for the fine-tune pipeline.
For the VOC, you use a 2-stage paradigm, 1) base training, 2) fine-tune on base+novel.
For COCO, you use a 3-stage paradigm, 1) base training, 2) novel training(only head), 3) fine-tune on base+novel

I wonder what's difference between these two types in motivation? and why use different paradigms for different datasets? Thanks.

**Comment by thomasehuang** [comment]
Hello,

Due to the increase in difficulty of COCO (and LVIS) compared to VOC, we found it helpful to initialize the novel weights first before fine-tuning. Better initialized weights make it easier for the model to learn during the fine-tuning stage, especially when there is a large number of object classes. For VOC, we did not find it necessary, so we just randomly initialized the novel weights.

Hope that helps!
