### ISSUE TITLE
Fine-tuning method used in paper

### ISSUE THREAD

**Issue by amajee11us** [ucbdrive/few-shot-object-detection#27]
There are two fine-tuning methods proposed in TRAIN_INST.md, one with random weights and the other with novel weights.
I could not locate the file : configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml

Also, in the paper what was the initialization that was performed for finetuning? Random weights or novel weights  and what was the difference in outcomes?

**Comment by forhadsidhu** [comment]
i think , using the random initialization just initialize last layer of detector model using random weight then fine tuned with novel data. on the other hand, first initialize last layer with novel weight then combine with base model and  fine tuned

> I could not locate the file : configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml

In configs/COCO-detections/ there are some yaml file for novel data

**Comment by thomasehuang** [comment]
Hello,

Since we didn't use the novel weights for PASCAL, we didn't include those config files here. You can look at the ones in the COCO directory for reference. I can also provide those config files if you really need them.

We study the effect of the weight initialization in section 4.3 of our [paper](https://arxiv.org/pdf/2003.06957.pdf). We used random weights on PASCAL and novel weights on COCO and LVIS. @forhadsidhu is correct in how the initialization works (thanks!). 

Hope that helps.

**Comment by amajee11us** [comment]
Thanks for the comment.

**Comment by Fly-dream12** [comment]
Hello,
when i use random weights on custom dataset, does it mean first generate the  model_reset_surgery.pth and then fine-tune with novel data using the config file "configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml"?
Could you provide the config file of PascalVOC, is there any difference from that of COCO?
Thanks,
@thomasehuang @ forhadsidhu
