### ISSUE TITLE
About experimental results

### ISSUE THREAD

**Issue by bominn** [ucbdrive/few-shot-object-detection#32]
Hi, thanks for sharing your great work.
I currently work on one-shot detection and would like to compare results on VOC dataset in your paper. Since both Table 1 and Table 7 contain results on VOC novel classes, is it suitable to use results in Table7 rather than Table1?  thanks.

**Comment by thomasehuang** [comment]
Hello, thank you for your interest.

For the results in table 7, we average the numbers across 30 different runs. If you are planning on using the same evaluation protocol (which we suggest), then you should compare to the results in table 7. Otherwise, if you are only using a single run, you should compare to the results in table 1.
