### ISSUE TITLE
ckpt_surgery on VOC like custom dataset

### ISSUE THREAD

**Issue by amajee11us** [ucbdrive/few-shot-object-detection#38]
I am using a custom dataset with annotations similar to VOC and the evaluation mechanism identified is also similar. In that regard I would like to perform a novel initialization before fine-tuning. The base dataset contains 7 classes and novel contains 3 classes (modified the codebase accordingly). When I try to perform a checkpoint combine.. i get the following error. Any help would be appreciated.
Traceback (most recent call last):
  File "tools/ckpt_surgery.py", line 311, in <module>
    combine_ckpts(args)
  File "tools/ckpt_surgery.py", line 143, in combine_ckpts
    surgery_loop(args, surgery)
  File "tools/ckpt_surgery.py", line 181, in surgery_loop
    surgery(param_name, False, tar_size, ckpt, ckpt2)
  File "tools/ckpt_surgery.py", line 125, in surgery
    ckpt2_weight = ckpt2['model'][weight_name]
KeyError: 'roi_heads.box_predictor.cls_score.bias'

I understand the error that the bias for the layer 'roi_heads.box_predictor.cls_score' is missing. But how can that be so is my question, and how can I avoid that?

**Comment by thomasehuang** [comment]
We set the bias to False for our cosine similarity based classifier. I'm guessing that you trained the base model with the FC classifier and the novel model with the cosine classifier and tried to combine them, which gives you this error. While we train both base and novel models with the same classifier, it should be okay to combine the weights anyways in your case, since we are further fine-tuning the weights. You can do either of these to fix the issue:
- Retrain novel model with FC classifier or retrain both base and novel models with cosine similarity based classifier, and then combine.
- Add another line in the code after [this](https://github.com/ucbdrive/few-shot-object-detection/blob/master/tools/ckpt_surgery.py#L84_L85) to do the same check for the second checkpoint. This will skip the combine step for the bias parameters.
```python
if not is_weight and param_name + '.bias' not in ckpt2['model']:
    return
```

Hope that helps!

**Comment by amajee11us** [comment]
Thanks for the reply :)

**Comment by SpringUp** [comment]
Hi, I am using a custom dataset which the base dataset contains 20 classes and novel contains 6 classes. When I try to perform a checkpoint combine.. i get the following error. Any help would be appreciated
#.roi_heads.box_predictor.cls_score.weight
#40 16
Traceback (most recent call last):
  File "tools/ckpt_surgery.py", line 263, in <module>
    combine_ckpts(args)
  File "tools/ckpt_surgery.py", line 135, in combine_ckpts
    surgery_loop(args, surgery)
  File "tools/ckpt_surgery.py", line 174, in surgery_loop
    surgery(param_name, True, tar_size, ckpt, ckpt2)
  File "tools/ckpt_surgery.py", line 128, in surgery
    new_weight[prev_cls:-1] = ckpt2_weight[:-1]
RuntimeError: The expanded size of the tensor (11) must match the existing size (26) at non-singleton dimension 0.  Target sizes: [11, 1024].  Tensor sizes: [26, 1024]
I want to know how to solve this size mismatch problem?

**Comment by pranay-ar** [comment]
> Hi, I am using a custom dataset which the base dataset contains 20 classes and novel contains 6 classes. When I try to perform a checkpoint combine.. i get the following error. Any help would be appreciated
> #.roi_heads.box_predictor.cls_score.weight
> #40 16
> Traceback (most recent call last):
> File "tools/ckpt_surgery.py", line 263, in
> combine_ckpts(args)
> File "tools/ckpt_surgery.py", line 135, in combine_ckpts
> surgery_loop(args, surgery)
> File "tools/ckpt_surgery.py", line 174, in surgery_loop
> surgery(param_name, True, tar_size, ckpt, ckpt2)
> File "tools/ckpt_surgery.py", line 128, in surgery
> new_weight[prev_cls:-1] = ckpt2_weight[:-1]
> RuntimeError: The expanded size of the tensor (11) must match the existing size (26) at non-singleton dimension 0. Target sizes: [11, 1024]. Tensor sizes: [26, 1024]
> I want to know how to solve this size mismatch problem?

Were you able to solve this error? I am also facing the same issue with my custom dataset of 9 base classes and 3 novel classes during the checkpoint combine stage.
