### ISSUE TITLE
infinite loop while preparing splits

### ISSUE THREAD

**Issue by manyaafonso** [ucbdrive/few-shot-object-detection#49]
Hi I have a 3 known class dataset and 2 novel classes. I am trying to prepare the splits according to prepare_coco_few_shot.py but for shots of 5 or more, for some classes the script gets stuck in an infinite loop. It works fine for the coco dataset. Any suggestion?

**Comment by thomasehuang** [comment]
With the COCO shots, we're assuming we can find a combination of images for each class such that the number of annotations sum up to exactly the number of shots we want. For your case, you might not have enough images for this to always happen. What you can do is remove [this](https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_coco_few_shot.py#L56) line and change [this](https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_coco_few_shot.py#L60) and the following if statement to `>=` instead of `==`. This will exit the while loop once you have enough shots. You also have to modify the COCO dataloader [here](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/datasets/meta_coco.py#L61) to only select _k_ shots from the list of annotations.
