### ISSUE TITLE
The issue about base train and novel train

### ISSUE THREAD

**Issue by myh12138** [ucbdrive/few-shot-object-detection#72]
During I train my own dataset,I met some problems, my owm dataset only has two classes. I have only one GPU 2080Ti , therefore I adjust the bachsize. However the result is so bad, the mAP is almost 0.1.  Also I find this program not has novel1_1shot.yaml in voc , threfore i copy one form coco and make some change , is there any problem with this? I hope  anyone can answer my questions.

**Comment by zyxfater** [comment]
Also I find this program not has novel1_1shot.yaml in voc

**Comment by jinweiLiu** [comment]
Did you find a solution? Where is the 'novel1_1shot.yaml' in voc? Look forward to your reply.

**Comment by g-lyc** [comment]
I have same problem，no solution.  T.T

**Comment by a07913838438** [comment]
no solution

**Comment by thomasehuang** [comment]
Apologies for the late response.

Regarding training on one GPU, the mAP being 0.1 is a little weird. You can reopen the issue and let me know if you still have this issue.

Regarding the novel file for VOC, see my answer in [this](https://github.com/ucbdrive/few-shot-object-detection/issues/13) issue. The reason why it's missing is because we don't do that step for VOC. I will update the README to make it more clear, sorry for the confusion.
