### ISSUE TITLE
Question about experimental results in paper

### ISSUE THREAD

**Issue by geonuk-kimmm** [ucbdrive/few-shot-object-detection#8]
Hi, thanks for sharing your work.
I well read your paper and found that there are 2 result on Pascal VOC.
In Figure 4, you shows the mAP over 30 random samples. And there is another mAP result in Table 1.
Is it the best mAP of your model? I noticed there were unreliable experimental report as you wrote. But still, i wonder how did you choose the result on Table 1.

Thanks :)

**Comment by thomasehuang** [comment]
Hello, thank you for your interest.

The mAP results in Table 1 are based on the setting used in previous works (see [https://arxiv.org/abs/1812.01866](https://arxiv.org/abs/1812.01866). The results on seed 0 refer to these results. You can think of it as just one random sample, instead of over 30 random samples.

Hope that helps!

**Comment by geonuk-kimmm** [comment]
> Hello, thank you for your interest.
> 
> The mAP results in Table 1 are based on the setting used in previous works (see https://arxiv.org/abs/1812.01866. The results on seed 0 refer to these results. You can think of it as just one random sample, instead of over 30 random samples.
> 
> Hope that helps!

Thanks.
So the seed 0 samples are exactly same with[ it ](https://github.com/bingykang/Fewshot_Detection/tree/master/data/vocsplit)?

**Comment by thomasehuang** [comment]
Yes! They should be the same.

**Comment by geonuk-kimmm** [comment]
Thanks!
