### ISSUE TITLE
COCO Structure

### ISSUE THREAD

**Issue by HeliosZhao** [ucbdrive/few-shot-object-detection#88]
Hi,

Thanks for your code, but I have a question about COCO.

When I finetune the novel weights on coco, I could not load the image.

```
python -m tools.train_net --num-gpus 1 \
        --config-file configs/COCO-detection/faster_rcnn_R_101_FPN_ft_novel_10shot.yaml \
        --opts MODEL.WEIGHTS checkpoints/coco/faster_rcnn/COCO_base_model/model_reset_remove.pth


```

The error is 
```
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/trainval2014/COCO_val2014_000000482978.jpg'

```

The coco data structure is the same with https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/README.md :

```
datasets/ 
    coco/
        train2014/
        val2014/
        annotations/
```

There is no dataset "trainval2014" ?

**Comment by davesie** [comment]
I fixed that by combining the two folder into one.
So it would look like this:
```
datasets/ 
    coco/
        train2014/
        val2014/
        trainval2014/
        annotations/
```

because if you take a look at [this](https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/builtin.py#L89) part where the dataset gets registered, they just register the val2014 and trainval2014 folder. The test2014 is not needed as I see it.

**Comment by HeliosZhao** [comment]
@davesie 
Yeah, it works fine. Thanks!

**Comment by davesie** [comment]
Glad I could help =)

**Comment by Wei-i** [comment]
> Glad I could help =)

thanks for your help for meeting the same issue:)))))
