### ISSUE TITLE
voc spilt1 1-shot ap:25.4

### ISSUE THREAD

**Issue by xiaoliqiangxxqzz** [ucbdrive/few-shot-object-detection#94]
Why did I reproduce the 1-shot result on Pascal Spilt1 with  AP of only 25.4?, using the base training model provided.
All configurations remain unchanged, except that only one GPU is used, and other parameters such as batchsize remain unchanged

**Comment by xinw1012** [comment]
Hey, sorry for the delayed response.  One quick note is that our configurations are designed for 8 GPUs and you will need to adjust the training schedule according to the linear scaling rule when you switch to a single GPU.  Also, the limited batch size in the single GPU setting might affect your experimental results. 

Another thing we advocate in the paper is to have multiple runs and compare the average performance and 95% confidence interval due to high variance in the few shot settings. We introduced a new benchmark with repeated runs and the variance interval. You may refer to the complete results of both base and novel classes on Pascal VOC and COCO can be found in Table 7 and Table 8 in the appendix of the arXiv version. https://arxiv.org/pdf/2003.06957.pdf

Hope it helps!

**Comment by Wei-i** [comment]
@xinw1012 
Thanks for your great work in FSOD! Recently many work follows your stand baseline.
I am confused about the G-FSOD. To be specific, I know the first rule which computes the base AP, novel AP, all AP. 
However, I am confused about the second rule where the code refers to "95% confidence interval". Could you give me some advice(e.g. give me a link or file.py to the corresponding codes)?
I would be grateful if you could reply:)

**Comment by thomasehuang** [comment]
> @xinw1012 Thanks for your great work in FSOD! Recently many work follows your stand baseline. I am confused about the G-FSOD. To be specific, I know the first rule which computes the base AP, novel AP, all AP. However, I am confused about the second rule where the code refers to "95% confidence interval". Could you give me some advice(e.g. give me a link or file.py to the corresponding codes)? I would be grateful if you could reply:)

The 95% confidence interval is computed on evaluation results across multiple runs, each with a different sample of the shots. You can refer to the README [here](https://github.com/ucbdrive/few-shot-object-detection#multiple-runs) for scripts to run the experiments and obtain the aggregated results.

**Comment by Wei-i** [comment]
> across

Thanks a lot for your help:))
